"""Public portal endpoints; user-specific settings live in config.py."""

DATAGOKR_CATALOG_URL = "https://api.odcloud.kr/api/15077093/v1"
DATAGOKR_PORTAL_URL = "https://www.data.go.kr/data"
DATAGOKR_OAS_URL = "https://infuser.odcloud.kr/oas/docs"
DATAGOKR_API_DETAIL_URL = "https://www.data.go.kr/tcs/dss/selectApiDetailFunction.do"
DATAGOKR_DATA_URL = "https://api.odcloud.kr/api"
DATAGOKR_ACCOUNT_URL = "https://www.data.go.kr/iim/api/selectAcountList.do"
DATAGOKR_APPLY_FORM_URL = "https://www.data.go.kr/tcs/dss/redirectDevAcountRequestForm.do"
DATAGOKR_APPLY_SAVE_URL = "https://www.data.go.kr/iim/api/saveMultiCloudApiRequest.do"
DATAGOKR_WEBFILTER_URL = "https://www.data.go.kr/cmm/wbf/webfilterCheck.json"
DATAGOKR_MEMBER_INFO_URL = "https://www.data.go.kr/uim/cmm/selectMberInfo.json"
DATAGOKR_DOWNLOAD_INFO_URL = "https://www.data.go.kr/tcs/dss/selectFileDataDownload.do"
DATAGOKR_DOWNLOAD_URL = "https://www.data.go.kr/cmm/cmm/fileDownload.do"
DATAGOKR_STD_COLUMNS_URL = "https://www.data.go.kr/download/columList.json"
DATAGOKR_STD_DATA_URL = "https://www.data.go.kr/download/standard.json"
DEFAULT_REMOTE_URL = "https://159-223-75-71.sslip.io/mcp"
